FROM keymetrics/pm2:14-alpine

ENV NODE_ENV=production
ENV PORT=6001

COPY index.js /srv/index.js
COPY package.json /srv/package.json
COPY pm2.json /srv/pm2.json
COPY src /srv/src

WORKDIR /srv

RUN npm install
RUN npm cache clean --force

EXPOSE 6001
CMD ["pm2-docker", "start", "pm2.json"]
